name: Mdc Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

  dev:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Fase de Desenvolvimento
        run: echo "Executando deploy de DEV"

  qa:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Fase de Qualidade
        run: echo "Executando deploy de QA"

  homologacao:
    needs:
      - dev
      - qa

    runs-on: ubuntu-latest

    steps:
      - name: Fase de Homologação
        run: echo "Executando deploy de HML"

  producao:
    needs: homologacao 
    runs-on: ubuntu-latest

    steps:
      - name: Fase de Produção
        run: echo "Executando deploy de PRD"