name: Runner Selection Workflow

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Choose the runner for the job'
        required: true
        type: choice
        default: 'ubuntu-latest'
        options:
          - 'ubuntu-latest'
          - 'macos-latest'

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Executando no Runner
        run: echo "Executando um Deploy usando um runner no input"